from tarun.print import print_slow
print_slow('Enter the string:')
a=input('>>')
print_slow('Enter the substring:')
sub=input('>>')
print_slow('Enter the substring:')
sub1=input('>>')
a=a.replace(sub,sub1)
print_slow('Modified string is:')
print(a)